export const ADD_POST = "ADD_POST";
export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const REMOVE_PRODUCT_BASKET = "REMOVE_PRODUCT_BASKET";
export const GET_NUMBER_BASKET = 'GET_NUMBER_BASKET'
